<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-LRQK3FVI" ignored="0" name="Banking Test 3(failed)" tests="7" failures="6" timestamp="12 Oct 2021 14:27:21 GMT" time="28.004" errors="0">
  <testcase name="checkData" time="3.607" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.549" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.56" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.778" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.74" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="3.323" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="StartTest" time="3.548" classname="Test_cases.Test_case_1"/>
</testsuite> <!-- Banking Test 3(failed) -->
