<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-LRQK3FVI" ignored="0" name="Banking Test 1(failed)" tests="8" failures="6" timestamp="12 Oct 2021 14:26:53 GMT" time="39.934" errors="0">
  <testcase name="checkData" time="3.245" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.499" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.741" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.775" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.744" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="checkData" time="2.768" classname="Test_cases.Test_case_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test_cases.Test_case_2.checkData(Test_case_2.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkData -->
  <testcase name="StartTest" time="2.986" classname="Test_cases.Test_case_1"/>
  <testcase name="addNewCustomer" time="8.396" classname="Test_cases.Test_case_3"/>
</testsuite> <!-- Banking Test 1(failed) -->
